version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: omcp
      POSTGRES_DB: omcp_service
      POSTGRES_PASSWORD: 1qazxsw2
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/posgresql/data
  omcp:
    build:
      context: .
    ports:
      - 8080:8000
    volumes:
      - ./omcp:/omcp
    command: python3 manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
volumes:
  pgdata: